# add your settings here (overriding the defaults)

biocypher:
  offline: true  # Generate CSV files only without trying to connect to Neo4j
  no_ontology: true  # Skip ontology validation completely
  schema_config_path: config/schema_config.yaml
  cache_directory: .cache
  strict_mode: false
  admin_port: 7474
  driver_port: 7687
  batch_size: 10000
  head_ontology:
    url: https://github.com/biolink/biolink-model/raw/v3.2.1/biolink-model.owl.ttl
    root_node: entity
    switch_label_and_id: true

neo4j:
  database_name: practice
  wipe: true
  uri: neo4j://localhost:7687
  username: neo4j
  password: "12345678"
  delimiter: '\t'
  array_delimiter: "|"
  skip_duplicate_nodes: false
  skip_bad_relationships: false
  multi_db: true

  labels_order: "Ascending"

  import_call_bin_prefix: bin/
  import_call_file_prefix: path/to/files/
