nodes:
  GenomicRegion:
    represented_as: node
    is_a: biolink:GenomicEntity
    properties:
      chromosome:
        type: string
      start:
        type: integer
      end:
        type: integer
      accession_e:
        type: string
      ccre_type:
        type: string
      distance_bp:
        type: integer
      source:
        type: string
      version:
        type: string
      license:
        type: string

  Gene:
    represented_as: node
    is_a: biolink:Gene
    properties:
      name:
        type: string
      source:
        type: string
      version:
        type: string
      license:
        type: string

relationships:
  RegionToGene:
    represented_as: edge
    source: GenomicRegion
    target: Gene
    is_a: biolink:related_to
    properties:
      distance_bp:
        type: integer
      source:
        type: string
      version:
        type: string
      license:
        type: string