nodes:
  GenomicRegion:
    represented_as: node
    preferred_id: SO:0000001
    label_in_input: "GenomicRegion"
    # id_prefix: GR
    is_a: biolink:GenomicEntity
    properties:
      chromosome:
        type: string
      start:
        type: integer
      end:
        type: integer
      accession_e:
        type: string
      ccre_type:
        type: string
      distance_bp:
        type: integer
      source:
        type: string
      version:
        type: string
      license:
        type: string

  Gene:
    represented_as: node
    preferred_id: SO:0000704  
    label_in_input: "Gene"
    # id_prefix: GENE
    is_a: biolink:Gene
    properties:
      name:
        type: string
      source:
        type: string
      version:
        type: string
      license:
        type: string

relationships:
  RegionToGene:
    represented_as: edge
    source: GenomicRegion
    target: Gene
    label_in_input: RegionToGene
    is_a: biolink:related_to
    properties:
      distance_bp:
        type: integer
      source:
        type: string
      version:
        type: string
      license:
        type: string